### PR TITLE
Update RegisterRoutePatterns.php

### PR DESCRIPTION
**Pull request by ospira**
Tokens in laravel are 64 characters not 60.

## PR Type

What kind of pull request is this? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Extend feature (non-breaking change which extends existing functionality)
- [ ] Change feature (non-breaking change which either changes or refactors existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## What does it change?

If I reset a password the token will 404 because of the character limit - 60 instead of 64.

## Why this PR?

Because without it I can't reset passwords in laravel 5.8 with this package.

## How has this been tested?

Tested and debugged on both hosted and local Laravel 5.8.

## Checklist

To facilitate merging your change and the approval of this PR, please make sure you've reviewed and applied the following:

- This PR addresses exactly one issue
- All changes were made in a fork of this project (preferably also in a separate branch)
- It follows the code style of this project
- Tests were added to cover the changes
- All previously existing tests still pass
- If the change to the code requires a change to the documentation, it has been updated accordingly

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by ospira** [comment]
To clarify - the default token in the password reset feature of laravel seems to be 64 characters not 60! Therefore, when using the password reset feature out of the box, it breaks using this package. Please let me know if you need any further clarification.

**Comment by ospira** [comment]
The travis check failed, if you agree with the change I can update the tests and the readme @sebastiaanluca ?

**Comment by ospira** [comment]
Went ahead and tried my hand at the tests/readme changes. Please let me know what you think and thank you for this package! 😊

**Comment by sebastiaanluca** [comment]
Thanks for your PR! Going to release a new version in a few minutes.

**Comment by ospira** [comment]
Thank you! 😊😊

**Pull request merged**
